name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Cela signifie qu'il s'exécutera lorsqu'un tag comme v1.0.0 sera poussé.

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Assure-toi d'utiliser la version Python que tu préfères

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build distribution
      run: |
        python setup.py sdist bdist_wheel  # Construire le package

    - name: Upload to PyPI
      run: |
        twine upload dist/*  # Upload sur PyPI
      env:
        TWINE_USERNAME: __token__   # Utilise '__token__' au lieu de ton nom d'utilisateur
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  # Utilise le secret pour le token PyPI
